= select-nrepl

https://github.com/eraserhd/select-nrepl[]

Text-object support for your editor as nREPL middleware. 

== Installing

Add the following to your `profiles.clj` (`cider-nrepl` isn't strictly
necessary, but if you want this, you probably want that, too):

.profiles.clj
[source,clojure]
----
{:user {:plugins [[cider/cider-nrepl "0.21.0"]]
        :dependencies [[net.eraserhead/select-nrepl "0.1.0"]]
        :repl-options {:nrepl-middleware [select-nrepl.core/wrap-select]}}}
----

This will add the "select" op to nrepl.  See the operation's descriptor for
more information.  You will need some editor scripting to use this operation.

== Demo

.Selecting elements
image::https://asciinema.org/a/235120.svg[link="https://asciinema.org/a/235120"]

.Selecting forms
image::https://asciinema.org/a/235116.svg[link="https://asciinema.org/a/235116"]

.Selecting toplevels
image::https://asciinema.org/a/235118.svg[link="https://asciinema.org/a/235118"]

== Kakoune

For intergrating with Kakoune, install https://github.com/eraserhd/rep[rep]
and see https://github.com/eraserhd/dotfiles/blob/develop/kak/config/kak.symlink/kakrc#L292-L38[this example].

== Note on Cursor Positions

In order to support as many editors as possible, columns are __zero-based
caret offsets__, meaning that they are not actually columns but specify the
location of a caret in between columns.  Zero is before the first character
on a line, and one is just after the first character.

== License

Copyright © 2019 Jason M. Felice

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0[].

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html[].
